# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

def common_pods
    pod 'ReachabilitySwift' # Network Info Tool
    pod 'CocoaAsyncSocket'
    pod 'CocoaLumberjack'
end


target 'HiTranslator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMLKit/TextRecognition'
  pod 'GoogleMLKit/TextRecognitionChinese'
  pod 'GoogleMLKit/TextRecognitionDevanagari'
  pod 'GoogleMLKit/TextRecognitionJapanese'
  pod 'GoogleMLKit/TextRecognitionKorean'
  pod 'GoogleMLKit/Translate'
  pod 'GoogleMLKit/LanguageID'
  pod 'FBSDKCoreKit'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'SnapKit'
  pod 'ZKProgressHUD'
  pod 'Alamofire'
  pod 'Firebase/RemoteConfig'
  pod 'Google-Mobile-Ads-SDK'
  
  common_pods
  # Pods for HiTranslator
end

target 'HiTranslatorProxy' do
  use_frameworks!
  common_pods
end
